import { expect, test } from '@playwright/test';

test('local board opens without login, filters jobs and saves evidence intake', async ({ page }, testInfo) => {
  const errors: string[] = [];
  page.on('pageerror', error => errors.push(error.message));
  await page.goto('/');
  await expect(page.getByLabel('Password', { exact: true })).toHaveCount(0);
  await expect(page.getByRole('heading', { name: 'Job board', exact: true })).toBeVisible();
  await expect(page.getByText('1 source requests failed.', { exact: false })).toBeVisible();
  await page.getByText('Source coverage', { exact: false }).click();
  await expect(page.getByRole('cell', { name: 'Fixture Greenhouse', exact: true })).toBeVisible();
  await expect(page.getByRole('cell', { name: '3 / 50', exact: true })).toBeVisible();
  await page.getByText('Source coverage', { exact: false }).click();
  await expect(page.getByRole('button', { name: 'Junior Data Engineer', exact: true })).toBeVisible();
  await expect(page.getByRole('button', { name: 'Software Engineer Intern', exact: true })).toHaveCount(0);
  await page.getByLabel('Time window').selectOption('0');
  await expect(page.getByRole('button', { name: 'Software Engineer Intern', exact: true })).toBeVisible();
  await page.getByLabel('Search jobs').fill('nothing-matches-this');
  await expect(page.getByRole('heading', { name: 'No postings in this view' })).toBeVisible();
  await page.getByLabel('Search jobs').fill('');
  await expect(page.getByRole('button', { name: 'Junior Data Engineer', exact: true })).toBeVisible();
  await page.screenshot({ path: testInfo.outputPath('board.png') });
  const postingLink = page.getByRole('link', { name: 'Open posting for Junior Data Engineer at Example Systems', exact: true });
  await expect(postingLink).toBeVisible();
  await expect(postingLink).toHaveAttribute('href', 'https://example.test/jobs/1');
  await expect(postingLink).toHaveAttribute('target', '_blank');
  await expect(postingLink).toHaveAttribute('rel', 'noopener noreferrer');
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true);
  expect(await page.evaluate(() => window.innerWidth)).toBe(page.viewportSize()!.width);
  await page.getByRole('button', { name: 'Junior Data Engineer', exact: true }).click();
  await expect(page.getByRole('dialog')).toBeVisible();
  await page.keyboard.press('Escape');
  await expect(page.getByRole('dialog')).toHaveCount(0);
  await page.getByRole('button', { name: 'Junior Data Engineer', exact: true }).click();
  await expect(page.getByText('No screening decision is saved', { exact: false })).toBeVisible();
  await page.getByRole('button', { name: 'Review evidence' }).click();
  await expect(page.getByLabel('Company', { exact: true })).toHaveValue('Example Systems');
  const bounds = await page.getByRole('dialog').boundingBox();
  expect(bounds).not.toBeNull();
  expect(bounds!.x).toBeGreaterThanOrEqual(0);
  expect(bounds!.x + bounds!.width).toBeLessThanOrEqual(page.viewportSize()!.width);
  await page.getByRole('button', { name: 'Save & review evidence' }).focus();
  await page.keyboard.press('Tab');
  await expect(page.getByRole('button', { name: 'Close', exact: true })).toBeFocused();
  await page.getByLabel('Full job description').fill('Seeking a junior engineer to build Python and SQL data pipelines, write automated tests, and maintain data validation workflows. This is a synthetic job description for local testing.');
  await page.screenshot({ path: testInfo.outputPath('intake.png') });
  await page.getByRole('button', { name: 'Faithful', exact: true }).click();
  await page.getByRole('button', { name: 'Save & review evidence' }).click();
  await expect(page.getByRole('heading', { name: 'Evidence workspace' })).toBeVisible();
  await expect(page.getByRole('heading', { name: 'Evidence candidates' })).toBeVisible();
  await expect(page.getByText('500 records.', { exact: false })).toBeVisible();
  await expect(page.getByText('Drafting and submission validation are not enabled', { exact: false })).toBeVisible();
  await page.screenshot({ path: testInfo.outputPath('evidence.png') });
  await page.getByRole('button', { name: 'Providers', exact: true }).click();
  await expect(page.getByRole('heading', { name: 'Model providers' })).toBeVisible();
  await expect(page.getByRole('heading', { name: 'Z.ai', exact: true })).toBeVisible();
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true);
  await expect(page.getByRole('button', { name: 'Sign out', exact: true })).toBeHidden();
  await page.reload();
  await expect(page.getByRole('heading', { name: 'Job board', exact: true })).toBeVisible();
  const response = await page.request.get('/api/jobs');
  expect(response.status()).toBe(200);
  expect(errors).toEqual([]);
});
