import { expect, test } from '@playwright/test';

test('owner login, board filtering, evidence intake, providers and logout', async ({ page }, testInfo) => {
  const errors: string[] = [];
  page.on('pageerror', error => errors.push(error.message));
  await page.goto('/');
  await expect(page.getByLabel('Email', { exact: true })).toBeVisible();
  await page.getByLabel('Email', { exact: true }).fill('owner@example.test');
  await page.getByLabel('Password', { exact: true }).fill('synthetic-password-123');
  await page.getByRole('button', { name: /Create account|Sign in/ }).click();
  await expect(page.getByRole('heading', { name: 'Job board', exact: true })).toBeVisible();
  await expect(page.getByRole('button', { name: 'Junior Data Engineer', exact: true })).toBeVisible();
  await expect(page.getByRole('button', { name: 'Software Engineer Intern', exact: true })).toHaveCount(0);
  await page.getByLabel('Time window').selectOption('0');
  await expect(page.getByRole('button', { name: 'Software Engineer Intern', exact: true })).toBeVisible();
  await page.getByLabel('Search jobs').fill('nothing-matches-this');
  await expect(page.getByRole('heading', { name: 'No postings in this view' })).toBeVisible();
  await page.getByLabel('Search jobs').fill('');
  await expect(page.getByRole('button', { name: 'Junior Data Engineer', exact: true })).toBeVisible();
  await page.screenshot({ path: testInfo.outputPath('board.png') });
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true);
  await page.getByRole('button', { name: 'Junior Data Engineer', exact: true }).click();
  await expect(page.getByRole('dialog')).toBeVisible();
  await page.getByRole('button', { name: 'Prepare application' }).click();
  await expect(page.getByLabel('Company', { exact: true })).toHaveValue('Example Systems');
  await page.getByLabel('Full job description').fill('Seeking a junior engineer to build Python and SQL data pipelines, write automated tests, and maintain data validation workflows. This is a synthetic job description for local testing.');
  await page.screenshot({ path: testInfo.outputPath('intake.png') });
  await page.getByRole('button', { name: 'Faithful', exact: true }).click();
  await page.getByRole('button', { name: 'Save & review evidence' }).click();
  await expect(page.getByRole('heading', { name: 'Evidence workspace' })).toBeVisible();
  await expect(page.getByRole('heading', { name: 'Evidence candidates' })).toBeVisible();
  await expect(page.getByText('500 records.', { exact: false })).toBeVisible();
  await expect(page.getByText('Drafting and submission validation are not enabled', { exact: false })).toBeVisible();
  await page.screenshot({ path: testInfo.outputPath('evidence.png') });
  await page.getByRole('button', { name: 'Providers', exact: true }).click();
  await expect(page.getByRole('heading', { name: 'Model providers' })).toBeVisible();
  await expect(page.getByRole('heading', { name: 'Z.ai', exact: true })).toBeVisible();
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true);
  await page.getByRole('button', { name: 'Sign out', exact: true }).click();
  await expect(page.getByRole('heading', { name: 'Welcome back' })).toBeVisible();
  const response = await page.request.get('/api/jobs');
  expect(response.status()).toBe(401);
  expect(errors).toEqual([]);
});
